openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /extractor/pib/:
    get:
      summary: Retornar Pib
      operationId: retornar_pib_extractor_pib__get
      parameters:
      - name: pais
        in: query
        required: true
        schema:
          type: string
          title: Pais
      - name: "a\xF1o"
        in: query
        required: true
        schema:
          type: integer
          title: "A\xF1o"
      - name: authorization
        in: header
        required: true
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /:
    get:
      summary: Read Root
      operationId: read_root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /validar-token/:
    post:
      summary: Validar Token
      operationId: validar_token_validar_token__post
      parameters:
      - name: authorization
        in: header
        required: true
        schema:
          type: string
          title: Authorization
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
